/**
 * The photography on the service detail pages.
 *
 * Generated by scripts/assign-service-photos.mjs: the slots a visitor sees
 * before scrolling are unique across the site and no page repeats a
 * photograph, so the pages stop looking like the same few pictures. Re-run
 * that script after adding photographs or changing a service's bullet points.
 */
import pai_02 from "@/assets/detail-ai-02.webp";
import pai_03 from "@/assets/detail-ai-03.webp";
import pai_04 from "@/assets/detail-ai-04.webp";
import pai_05 from "@/assets/detail-ai-05.webp";
import pai_06 from "@/assets/detail-ai-06.webp";
import pai_07 from "@/assets/detail-ai-07.webp";
import panalytics from "@/assets/detail-analytics.webp";
import papp_01 from "@/assets/detail-app-01.webp";
import papp_02 from "@/assets/detail-app-02.webp";
import papp_03 from "@/assets/detail-app-03.webp";
import papp_04 from "@/assets/detail-app-04.webp";
import papp_05 from "@/assets/detail-app-05.webp";
import papp_06 from "@/assets/detail-app-06.webp";
import papp_07 from "@/assets/detail-app-07.webp";
import papp_08 from "@/assets/detail-app-08.webp";
import papp_09 from "@/assets/detail-app-09.webp";
import papp_10 from "@/assets/detail-app-10.webp";
import patl_events from "@/assets/photo-integrated-campaigns.webp";
import patl_outdoor from "@/assets/photo-outdoor-print.webp";
import patl_planning from "@/assets/photo-campaign-planning.webp";
import patl_traditional from "@/assets/photo-traditional-media.webp";
import pcamera from "@/assets/detail-camera.webp";
import pcampaign from "@/assets/detail-campaign.webp";
import pcode_01 from "@/assets/detail-code-01.webp";
import pcode_02 from "@/assets/detail-code-02.webp";
import pcode_03 from "@/assets/detail-code-03.webp";
import pcode_04 from "@/assets/detail-code-04.webp";
import pcode_05 from "@/assets/detail-code-05.webp";
import pcode_06 from "@/assets/detail-code-06.webp";
import pcode_07 from "@/assets/detail-code-07.webp";
import pcode_08 from "@/assets/detail-code-08.webp";
import pcode_10 from "@/assets/detail-code-10.webp";
import pcode_11 from "@/assets/detail-code-11.webp";
import pcode_12 from "@/assets/detail-code-12.webp";
import pcode_13 from "@/assets/detail-code-13.webp";
import pcontent from "@/assets/detail-content.webp";
import pcreative from "@/assets/detail-creative.webp";
import pdata_01 from "@/assets/detail-data-01.webp";
import pdata_02 from "@/assets/detail-data-02.webp";
import pdata_03 from "@/assets/detail-data-03.webp";
import pdata_04 from "@/assets/detail-data-04.webp";
import pdata_05 from "@/assets/detail-data-05.webp";
import pdata_06 from "@/assets/detail-data-06.webp";
import pdata_07 from "@/assets/detail-data-07.webp";
import pdata_10 from "@/assets/detail-data-10.webp";
import pdesign from "@/assets/detail-design.webp";
import pdesk_01 from "@/assets/detail-desk-01.webp";
import pdesk_02 from "@/assets/detail-desk-02.webp";
import pdesk_03 from "@/assets/detail-desk-03.webp";
import pdesk_04 from "@/assets/detail-desk-04.webp";
import pdesk_05 from "@/assets/detail-desk-05.webp";
import pdesk_07 from "@/assets/detail-desk-07.webp";
import pdesk_08 from "@/assets/detail-desk-08.webp";
import pdesk_09 from "@/assets/detail-desk-09.webp";
import pdesk_10 from "@/assets/detail-desk-10.webp";
import pdesk_11 from "@/assets/detail-desk-11.webp";
import plaptop from "@/assets/detail-laptop.webp";
import pmark_01 from "@/assets/detail-mark-01.webp";
import pmark_03 from "@/assets/detail-mark-03.webp";
import pmark_05 from "@/assets/detail-mark-05.webp";
import pmark_08 from "@/assets/detail-mark-08.webp";
import pmark_09 from "@/assets/detail-mark-09.webp";
import pmark_10 from "@/assets/detail-mark-10.webp";
import pmob_01 from "@/assets/detail-mob-01.webp";
import pmob_02 from "@/assets/detail-mob-02.webp";
import pmob_03 from "@/assets/detail-mob-03.webp";
import pmob_04 from "@/assets/detail-mob-04.webp";
import pmob_05 from "@/assets/detail-mob-05.webp";
import pmob_06 from "@/assets/detail-mob-06.webp";
import pmob_07 from "@/assets/detail-mob-07.webp";
import pmob_08 from "@/assets/detail-mob-08.webp";
import pmobile from "@/assets/detail-mobile.webp";
import pooh_01 from "@/assets/detail-ooh-01.webp";
import pooh_02 from "@/assets/detail-ooh-02.webp";
import pooh_03 from "@/assets/detail-ooh-03.webp";
import pooh_09 from "@/assets/detail-ooh-09.webp";
import pooh_10 from "@/assets/detail-ooh-10.webp";
import pooh_11 from "@/assets/detail-ooh-11.webp";
import pooh_12 from "@/assets/detail-ooh-12.webp";
import pplan_02 from "@/assets/detail-plan-02.webp";
import pplan_03 from "@/assets/detail-plan-03.webp";
import pplan_05 from "@/assets/detail-plan-05.webp";
import pplan_06 from "@/assets/detail-plan-06.webp";
import pplan_07 from "@/assets/detail-plan-07.webp";
import pplan_08 from "@/assets/detail-plan-08.webp";
import pplan_09 from "@/assets/detail-plan-09.webp";
import pplan_10 from "@/assets/detail-plan-10.webp";
import pplan_11 from "@/assets/detail-plan-11.webp";
import pplan_12 from "@/assets/detail-plan-12.webp";
import pplanning from "@/assets/detail-planning.webp";
import ppresentation from "@/assets/detail-presentation.webp";
import presearch from "@/assets/detail-research.webp";
import psocial from "@/assets/detail-social.webp";
import pstrategy from "@/assets/detail-strategy.webp";
import pteam_01 from "@/assets/detail-team-01.webp";
import pteam_02 from "@/assets/detail-team-02.webp";
import pteam_04 from "@/assets/detail-team-04.webp";
import pteam_05 from "@/assets/detail-team-05.webp";
import pteam_06 from "@/assets/detail-team-06.webp";
import pteam_07 from "@/assets/detail-team-07.webp";
import pteam_09 from "@/assets/detail-team-09.webp";
import pteam_10 from "@/assets/detail-team-10.webp";
import pteam_11 from "@/assets/detail-team-11.webp";
import pteam_13 from "@/assets/detail-team-13.webp";
import pteam_15 from "@/assets/detail-team-15.webp";
import pteam_16 from "@/assets/detail-team-16.webp";
import pteam_17 from "@/assets/detail-team-17.webp";
import pteam_18 from "@/assets/detail-team-18.webp";
import pteam_20 from "@/assets/detail-team-20.webp";
import pteam_21 from "@/assets/detail-team-21.webp";
import pvid_01 from "@/assets/detail-vid-01.webp";
import pvid_02 from "@/assets/detail-vid-02.webp";
import pvid_03 from "@/assets/detail-vid-03.webp";
import pvid_04 from "@/assets/detail-vid-04.webp";
import pvid_05 from "@/assets/detail-vid-05.webp";
import pvid_06 from "@/assets/detail-vid-06.webp";
import pvid_07 from "@/assets/detail-vid-07.webp";
import pvid_09 from "@/assets/detail-vid-09.webp";
import pworkshop from "@/assets/detail-workshop.webp";
import pworkspace from "@/assets/detail-workspace.webp";
import pwriting from "@/assets/detail-writing.webp";

const photos: Record<string, { src: string; alt: string }> = {
  "ai-02": { src: pai_02, alt: "A team working at their computers" },
  "ai-03": { src: pai_03, alt: "Three colleagues in an open office" },
  "ai-04": { src: pai_04, alt: "A working floor of computers" },
  "ai-05": { src: pai_05, alt: "Working late at a screen" },
  "ai-06": { src: pai_06, alt: "A laptop running an automation tool" },
  "ai-07": { src: pai_07, alt: "A relaxed studio office" },
  "analytics": { src: panalytics, alt: "Marketing analytics" },
  "app-01": { src: papp_01, alt: "A phone held in the hand" },
  "app-02": { src: papp_02, alt: "Using an app on a phone" },
  "app-03": { src: papp_03, alt: "A phone on a plain surface" },
  "app-04": { src: papp_04, alt: "An app open on a phone" },
  "app-05": { src: papp_05, alt: "Testing a screen against its sketch" },
  "app-06": { src: papp_06, alt: "Working on a tablet at a table" },
  "app-07": { src: papp_07, alt: "Sketching an interface on paper" },
  "app-08": { src: papp_08, alt: "Drawing up app screens" },
  "app-09": { src: papp_09, alt: "Wireframes drawn on paper" },
  "app-10": { src: papp_10, alt: "App screens laid out on a desk" },
  "atl-events": { src: patl_events, alt: "A live event audience" },
  "atl-outdoor": { src: patl_outdoor, alt: "Printed newspapers and press" },
  "atl-planning": { src: patl_planning, alt: "Planning a campaign at a desk" },
  "atl-traditional": { src: patl_traditional, alt: "Television advertising at home" },
  "camera": { src: pcamera, alt: "A content production camera" },
  "campaign": { src: pcampaign, alt: "Campaign planning in progress" },
  "code-01": { src: pcode_01, alt: "Lines of markup on screen" },
  "code-02": { src: pcode_02, alt: "Application code on a monitor" },
  "code-03": { src: pcode_03, alt: "Source code on a screen" },
  "code-04": { src: pcode_04, alt: "A monitor and laptop open on a build" },
  "code-05": { src: pcode_05, alt: "Markup for a web project" },
  "code-06": { src: pcode_06, alt: "A two-screen development setup" },
  "code-07": { src: pcode_07, alt: "A code editor in a dark theme" },
  "code-08": { src: pcode_08, alt: "A laptop open on a codebase" },
  "code-10": { src: pcode_10, alt: "Component code in an editor" },
  "code-11": { src: pcode_11, alt: "A laptop set up for development" },
  "code-12": { src: pcode_12, alt: "A developer at work" },
  "code-13": { src: pcode_13, alt: "Back-end code in a dark workspace" },
  "content": { src: pcontent, alt: "A content workspace" },
  "creative": { src: pcreative, alt: "A creative workspace" },
  "data-01": { src: pdata_01, alt: "A search performance report" },
  "data-02": { src: pdata_02, alt: "A campaign dashboard with cost and quality figures" },
  "data-03": { src: pdata_03, alt: "Working through reports on a laptop" },
  "data-04": { src: pdata_04, alt: "A performance trend line on screen" },
  "data-05": { src: pdata_05, alt: "A site overview report" },
  "data-06": { src: pdata_06, alt: "An analytics view on a screen" },
  "data-07": { src: pdata_07, alt: "Search impressions and click figures" },
  "data-10": { src: pdata_10, alt: "Searching on a laptop at a cafe table" },
  "design": { src: pdesign, alt: "A design workspace" },
  "desk-01": { src: pdesk_01, alt: "A working desk with laptop and monitor" },
  "desk-02": { src: pdesk_02, alt: "A studio desk and screen" },
  "desk-03": { src: pdesk_03, alt: "A desk set up for writing and planning" },
  "desk-04": { src: pdesk_04, alt: "A quiet office desk" },
  "desk-05": { src: pdesk_05, alt: "A design workstation" },
  "desk-07": { src: pdesk_07, alt: "A desk by a window" },
  "desk-08": { src: pdesk_08, alt: "Printed colour swatches and palettes" },
  "desk-09": { src: pdesk_09, alt: "A designer working across two screens" },
  "desk-10": { src: pdesk_10, alt: "The word create set out in wooden letters" },
  "desk-11": { src: pdesk_11, alt: "An editing timeline open on a laptop" },
  "laptop": { src: plaptop, alt: "A digital team at work" },
  "mark-01": { src: pmark_01, alt: "A row of review stars" },
  "mark-03": { src: pmark_03, alt: "Filling in a form on a laptop" },
  "mark-05": { src: pmark_05, alt: "Branded stationery laid out together" },
  "mark-08": { src: pmark_08, alt: "A brand sign on a building" },
  "mark-09": { src: pmark_09, alt: "Printed brand cards laid out" },
  "mark-10": { src: pmark_10, alt: "A brand guidelines book open on a spread" },
  "mob-01": { src: pmob_01, alt: "Social media apps on a phone screen" },
  "mob-02": { src: pmob_02, alt: "A social feed open on a phone" },
  "mob-03": { src: pmob_03, alt: "Working across a phone and a laptop" },
  "mob-04": { src: pmob_04, alt: "A social folder open on a phone" },
  "mob-05": { src: pmob_05, alt: "Browsing a profile grid on a phone" },
  "mob-06": { src: pmob_06, alt: "A photo grid on a phone beside a laptop" },
  "mob-07": { src: pmob_07, alt: "An advertising app open on a phone" },
  "mob-08": { src: pmob_08, alt: "Running a search on a phone" },
  "mobile": { src: pmobile, alt: "A mobile digital experience" },
  "ooh-01": { src: pooh_01, alt: "A street advertising panel in the city" },
  "ooh-02": { src: pooh_02, alt: "An empty billboard against the sky" },
  "ooh-03": { src: pooh_03, alt: "A roadside billboard" },
  "ooh-09": { src: pooh_09, alt: "A billboard lit against the night sky" },
  "ooh-10": { src: pooh_10, alt: "A billboard carrying a short message" },
  "ooh-11": { src: pooh_11, alt: "A bus stop advertising panel" },
  "ooh-12": { src: pooh_12, alt: "City streets lined with advertising" },
  "plan-02": { src: pplan_02, alt: "Two people mapping ideas on a whiteboard" },
  "plan-03": { src: pplan_03, alt: "Diagrams drawn on a glass whiteboard" },
  "plan-05": { src: pplan_05, alt: "Wireframes and sticky notes on a glass wall" },
  "plan-06": { src: pplan_06, alt: "A content calendar planned out on a board" },
  "plan-07": { src: pplan_07, alt: "A roadmap sketched on a whiteboard" },
  "plan-08": { src: pplan_08, alt: "A planning board of grouped sticky notes" },
  "plan-09": { src: pplan_09, alt: "Sketching a process on a whiteboard" },
  "plan-10": { src: pplan_10, alt: "A workflow mapped out step by step" },
  "plan-11": { src: pplan_11, alt: "The word audience written on a whiteboard" },
  "plan-12": { src: pplan_12, alt: "A weekly content plan on a board" },
  "planning": { src: pplanning, alt: "A team planning meeting" },
  "presentation": { src: ppresentation, alt: "Colleagues working through a presentation" },
  "research": { src: presearch, alt: "Digital research and planning" },
  "social": { src: psocial, alt: "Social media applications" },
  "strategy": { src: pstrategy, alt: "Business strategy and documents" },
  "team-01": { src: pteam_01, alt: "A team reviewing notes around a meeting table" },
  "team-02": { src: pteam_02, alt: "Colleagues seated in a workshop session" },
  "team-04": { src: pteam_04, alt: "Colleagues with laptops in a board meeting" },
  "team-05": { src: pteam_05, alt: "A project team seated around a table" },
  "team-06": { src: pteam_06, alt: "Colleagues gathered around a laptop" },
  "team-07": { src: pteam_07, alt: "A planning session around a shared table" },
  "team-09": { src: pteam_09, alt: "A client meeting in progress" },
  "team-10": { src: pteam_10, alt: "Colleagues working at laptops together" },
  "team-11": { src: pteam_11, alt: "A bright meeting room during a working session" },
  "team-13": { src: pteam_13, alt: "A team reviewing work together" },
  "team-15": { src: pteam_15, alt: "Two specialists working through a task" },
  "team-16": { src: pteam_16, alt: "A working discussion at a desk" },
  "team-17": { src: pteam_17, alt: "An open-plan studio at work" },
  "team-18": { src: pteam_18, alt: "A team working across a long table" },
  "team-20": { src: pteam_20, alt: "Colleagues working side by side at their screens" },
  "team-21": { src: pteam_21, alt: "A workshop session at a whiteboard" },
  "vid-01": { src: pvid_01, alt: "A film crew working on a lit set" },
  "vid-02": { src: pvid_02, alt: "A production crew setting up a shoot" },
  "vid-03": { src: pvid_03, alt: "A videographer checking a shot" },
  "vid-04": { src: pvid_04, alt: "A production camera recording in a studio" },
  "vid-05": { src: pvid_05, alt: "A clapperboard on set" },
  "vid-06": { src: pvid_06, alt: "Filming on location" },
  "vid-07": { src: pvid_07, alt: "A production video camera" },
  "vid-09": { src: pvid_09, alt: "Filming an interview" },
  "workshop": { src: pworkshop, alt: "A collaborative workshop" },
  "workspace": { src: pworkspace, alt: "A professional workspace" },
  "writing": { src: pwriting, alt: "Writing and research" },
};

const orders: Record<string, string[]> = {
  "digital-marketing": ["campaign", "planning", "team-04", "team-09", "team-21", "laptop"],
  "marketing-business-automation": ["analytics", "data-04", "data-10", "ai-06", "data-01", "data-05"],
  "brand-management": ["mark-01", "mark-09", "desk-05", "workspace", "mark-03", "mark-10"],
  "atl-ttl-campaigns": ["ooh-01", "ooh-02", "ooh-09", "ooh-11", "ooh-03", "ooh-10"],
  "website-development": ["code-01", "code-02", "code-03", "code-04", "code-06", "code-07"],
  "app-development": ["app-01", "app-02", "app-03", "app-04", "app-05", "app-06"],
  "custom-ai-development": ["ai-02", "ai-03", "ai-04", "ai-07", "ai-05", "ai-06"],
  "graphic-design": ["content", "desk-01", "desk-07", "writing", "creative", "design"],
  "video-editing-animation": ["camera", "vid-01", "vid-03", "vid-05", "vid-09", "vid-02"],
  "seo-services": ["data-01", "data-05", "plan-08", "research", "analytics", "data-04", "data-10", "strategy"],
  "ppc-management": ["data-02", "data-06", "plan-09", "strategy", "data-03", "data-07", "plan-10", "research", "social", "mob-02", "app-07", "app-01"],
  "social-media-marketing": ["mob-01", "mob-02", "mob-03", "mob-04", "mob-06", "mob-07", "mob-08", "mobile", "mob-05", "social", "app-08", "app-02", "app-09", "atl-outdoor", "atl-planning", "atl-traditional"],
  "content-marketing": ["creative", "desk-02", "desk-08", "vid-06", "content", "desk-03", "desk-04", "desk-10", "vid-04", "vid-09", "app-09", "app-03"],
  "crm-integration": ["data-03", "data-07", "ai-05", "team-10", "data-02", "data-06", "ai-02", "ai-03", "ai-07", "workshop", "code-01", "code-12"],
  "lead-nurturing": ["laptop", "presentation", "team-05", "team-11", "workshop", "planning", "team-02", "team-06", "team-13", "mob-03", "app-10", "app-04", "app-08"],
  "workflow-automation": ["plan-02", "plan-05", "plan-10", "code-05", "plan-03", "plan-06", "plan-09", "ai-04", "code-08", "code-10", "code-02", "code-13", "app-10"],
  "brand-positioning": ["plan-03", "plan-06", "plan-11", "team-13", "plan-02", "plan-07", "plan-12", "team-07", "team-15", "mob-04", "code-03", "app-05"],
  "brand-guidelines-voice": ["mark-03", "mark-10", "desk-09", "team-15", "mark-01", "mark-09", "desk-07", "desk-11", "team-16", "mob-06", "code-04", "app-06", "atl-events"],
  "brand-consistency": ["mark-05", "desk-03", "desk-10", "mob-05", "mark-08", "desk-02", "desk-08", "workspace", "mob-01", "mob-07", "code-05"],
  "reputation-management": ["mark-08", "team-01", "team-06", "team-16", "mark-05", "presentation", "team-04", "team-09", "team-17", "mob-08"],
  "email-marketing": ["design", "desk-04", "desk-11", "team-17", "desk-01", "desk-05", "desk-09", "writing", "team-18", "mobile", "code-06", "app-07"],
  "traditional-media-advertising": ["atl-traditional", "vid-02", "vid-04", "vid-07", "camera", "vid-01", "vid-03", "vid-05", "vid-06", "ooh-12", "code-07"],
  "outdoor-print-advertising": ["atl-outdoor", "ooh-03", "ooh-10", "ooh-12", "ooh-01", "ooh-02", "ooh-09", "ooh-11", "vid-07", "code-11", "code-08"],
  "integrated-marketing-campaigns": ["atl-events", "team-02", "team-07", "team-18", "campaign", "team-01", "team-05", "team-10", "team-20", "code-12", "code-10"],
  "campaign-planning-execution": ["atl-planning", "plan-07", "plan-12", "team-20", "plan-05", "plan-08", "plan-11", "team-11", "team-21", "code-13", "code-11"],
};

/**
 * The photograph for a slot: 0 is the hero, 1 the overview, then one per
 * bullet point section. A service that gains a bullet point in the admin
 * panel reuses its own photographs rather than leaving a gap.
 */
export function servicePhoto(slug: string, position: number) {
  const list = orders[slug];
  if (!list?.length) return { src: "", alt: "" };
  return photos[list[position % list.length]];
}

// Additional campaign photographs
import atlPhoto3 from "@/assets/photo-campaign-planning.webp";
import atlPhoto2 from "@/assets/photo-integrated-campaigns.webp";
import atlPhoto1 from "@/assets/photo-outdoor-print.webp";
import atlPhoto0 from "@/assets/photo-traditional-media.webp";
photos["atl-0"] = { src: atlPhoto0, alt: "Television advertising context" };
orders["traditional-media-advertising"] = [
  "atl-0",
  "research",
  "strategy",
  "planning",
  "campaign",
  "laptop",
  "writing",
  "content",
  "design",
  "workspace",
  "presentation",
];
photos["atl-1"] = { src: atlPhoto1, alt: "Printed newspapers and media" };
orders["outdoor-print-advertising"] = [
  "atl-1",
  "plan-02",
  "plan-03",
  "plan-05",
  "plan-06",
  "plan-07",
  "plan-08",
  "plan-09",
  "plan-10",
  "plan-11",
  "plan-12",
];
photos["atl-2"] = { src: atlPhoto2, alt: "Live event presentation" };
orders["integrated-marketing-campaigns"] = [
  "atl-2",
  "team-01",
  "team-02",
  "team-04",
  "team-05",
  "team-06",
  "team-07",
  "team-09",
  "team-10",
  "team-11",
  "team-13",
];
photos["atl-3"] = { src: atlPhoto3, alt: "Campaign planning workspace" };
orders["campaign-planning-execution"] = [
  "atl-3",
  "team-15",
  "team-16",
  "team-17",
  "team-18",
  "team-20",
  "team-21",
  "desk-01",
  "desk-02",
  "desk-03",
  "desk-04",
];
orders["atl-ttl-campaigns"] = ["vid-01", "vid-02", "vid-03", "vid-04", "vid-05", "vid-06"];
