import { imageFor } from "./images";
const subjects: Record<string, string> = {
  research: "Digital research and planning",
  analytics: "Marketing analytics",
  strategy: "Business strategy and documents",
  workshop: "Collaborative workshop",
  planning: "Team planning meeting",
  campaign: "Campaign planning",
  creative: "Creative workspace",
  laptop: "Digital team working",
  mobile: "Mobile digital experience",
  writing: "Writing and research",
  content: "Content workspace",
  camera: "Content production camera",
  design: "Design workspace",
  social: "Social media applications",
  presentation: "Business collaboration",
  workspace: "Professional workspace",
};
const orders: Record<string, string[]> = {
  "digital-marketing": [
    "presentation",
    "strategy",
    "analytics",
    "social",
    "campaign",
    "writing",
    "research",
    "workshop",
    "planning",
    "creative",
    "laptop",
    "mobile",
    "content",
    "camera",
    "design",
    "workspace",
  ],
  "seo-services": [
    "research",
    "analytics",
    "laptop",
    "creative",
    "mobile",
    "planning",
    "strategy",
    "workspace",
    "workshop",
    "campaign",
    "writing",
    "content",
    "camera",
    "design",
    "social",
    "presentation",
  ],
  "ppc-management": [
    "campaign",
    "strategy",
    "analytics",
    "planning",
    "research",
    "mobile",
    "social",
    "creative",
    "workshop",
    "laptop",
    "content",
    "presentation",
    "writing",
    "camera",
    "design",
    "workspace",
  ],
  "social-media-marketing": [
    "social",
    "mobile",
    "strategy",
    "creative",
    "camera",
    "writing",
    "content",
    "planning",
    "workshop",
    "analytics",
    "research",
    "campaign",
    "design",
    "laptop",
    "presentation",
    "workspace",
  ],
  "content-marketing": [
    "writing",
    "content",
    "strategy",
    "research",
    "creative",
    "design",
    "camera",
    "social",
    "mobile",
    "planning",
    "campaign",
    "analytics",
    "workshop",
    "laptop",
    "presentation",
    "workspace",
  ],
};

orders["brand-management"] = [
  "strategy",
  "design",
  "research",
  "analytics",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "laptop",
  "mobile",
  "writing",
  "content",
  "camera",
  "social",
  "presentation",
  "workspace",
];
orders["marketing-business-automation"] = [
  "analytics",
  "laptop",
  "research",
  "strategy",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "social",
  "presentation",
  "workspace",
];
orders["crm-integration"] = [
  "analytics",
  "research",
  "strategy",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "laptop",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "social",
  "presentation",
  "workspace",
];
orders["lead-nurturing"] = [
  "campaign",
  "strategy",
  "research",
  "analytics",
  "workshop",
  "planning",
  "creative",
  "laptop",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "social",
  "presentation",
  "workspace",
];
orders["workflow-automation"] = [
  "laptop",
  "analytics",
  "research",
  "strategy",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "social",
  "presentation",
  "workspace",
];
orders["brand-positioning"] = [
  "strategy",
  "research",
  "analytics",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "laptop",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "social",
  "presentation",
  "workspace",
];
orders["brand-guidelines-voice"] = [
  "design",
  "writing",
  "research",
  "analytics",
  "strategy",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "laptop",
  "mobile",
  "content",
  "camera",
  "social",
  "presentation",
  "workspace",
];
orders["brand-consistency"] = [
  "creative",
  "social",
  "research",
  "analytics",
  "strategy",
  "workshop",
  "planning",
  "campaign",
  "laptop",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "presentation",
  "workspace",
];
orders["reputation-management"] = [
  "research",
  "presentation",
  "analytics",
  "strategy",
  "workshop",
  "planning",
  "campaign",
  "creative",
  "laptop",
  "mobile",
  "writing",
  "content",
  "camera",
  "design",
  "social",
  "workspace",
];

orders["email-marketing"] = [
  "writing",
  "content",
  "strategy",
  "analytics",
  "creative",
  "mobile",
  "camera",
  "laptop",
  "research",
  "planning",
  "campaign",
  "workspace",
  "workshop",
  "design",
  "social",
  "presentation",
];

export function servicePhoto(slug: string, position: number) {
  const name = orders[slug]?.[position];
  if (!name) throw new Error(`Missing service photograph: ${slug}, position ${position}`);
  return { src: imageFor(`detail-${name}`), alt: subjects[name] };
}
