/**
 * Builds the deployable content admin into dist-static/<ADMIN_PATH>/.
 *
 * The editor ships inside the site's own upload, so it is reached at
 * https://the-site/<ADMIN_PATH>/ with no extra hosting. Its backend is
 * admin/server/api.php, which reads and commits content on GitHub — the web
 * host stores nothing, so there is no second copy of the content to drift.
 *
 * Everything secret is written into config.php, which the folder's .htaccess
 * refuses to serve.
 *
 * Required environment:
 *   ADMIN_PATH           the folder name, e.g. "studio-7fa2c1"
 *   ADMIN_PASSWORD_HASH  the value npm run admin:password prints
 *   ADMIN_GITHUB_TOKEN   a token that can read and write the repository
 *   ADMIN_GITHUB_REPO    "owner/name"
 *
 * Optional:
 *   ADMIN_GITHUB_BRANCH    default "main"
 *   ADMIN_GITHUB_WORKFLOW  default "deploy.yml"
 *
 * Run with: npm run build:admin
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";
import { iconCatalog } from "./icon-catalog.mjs";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const env = {
  path: process.env.ADMIN_PATH,
  hash: process.env.ADMIN_PASSWORD_HASH,
  token: process.env.ADMIN_GITHUB_TOKEN,
  repo: process.env.ADMIN_GITHUB_REPO,
  branch: process.env.ADMIN_GITHUB_BRANCH || "main",
  workflow: process.env.ADMIN_GITHUB_WORKFLOW || "deploy.yml",
};

// No ADMIN_PATH means the live editor has not been set up yet. That is a valid
// state — the site deploys without it — so say so and stop rather than failing
// the deployment.
if (!env.path) {
  console.log("\n  ADMIN_PATH is not set, so the live editor was not built.");
  console.log("  The site itself is unaffected. See admin/README.md to set it up.\n");
  process.exit(0);
}

/**
 * Stops with a reason that can be read without opening the build log.
 *
 * On Actions, ::error:: puts the text on the run's summary page — which is
 * where someone who has just set a secret wrongly will actually be looking.
 *
 * @param {string} reason What is wrong.
 * @param {string} fix    What to do about it.
 */
function stop(reason, fix) {
  if (process.env.GITHUB_ACTIONS) {
    console.log("::error title=Content admin not built::" + reason + " " + fix);
  }
  console.error("\n  " + reason);
  console.error("  " + fix + "\n");
  process.exit(1);
}

const missing = ["hash", "token", "repo"].filter((key) => !env[key]);

if (missing.length) {
  const names = {
    hash: "ADMIN_PASSWORD_HASH",
    token: "ADMIN_GITHUB_TOKEN",
    repo: "ADMIN_GITHUB_REPO",
  };
  const listed = missing.map((key) => names[key]);
  const readable =
    listed.length === 1 ? listed[0] : listed.slice(0, -1).join(", ") + " and " + listed.at(-1);

  stop(
    `ADMIN_PATH is set but ${readable} ${listed.length === 1 ? "is" : "are"} missing.`,
    "Add the missing repository secret(s) — see admin/README.md.",
  );
}

if (!/^[a-z0-9][a-z0-9-]{3,63}$/.test(env.path)) {
  stop(
    `ADMIN_PATH is "${env.path}", which is not a usable folder name.`,
    "It must be 4-64 characters of lower-case letters, numbers and hyphens — no slashes, spaces or capitals. For example: studio-7fa2c19e",
  );
}

// A hash, never a password. Anything else here would put the password itself
// into the deployed files.
if (!/^pbkdf2\$[a-z0-9]+\$\d+\$[0-9a-f]+\$[0-9a-f]+$/.test(env.hash)) {
  stop(
    "ADMIN_PASSWORD_HASH is not in the expected form.",
    "It must be the whole pbkdf2$… line that `npm run admin:password` prints — not the password itself.",
  );
}

const outDir = path.join(rootDir, "dist-static", env.path);

/* ------------------------------------------------------------------
   The editor itself
------------------------------------------------------------------ */

await build({
  configFile: path.join(rootDir, "admin/vite.config.ts"),
  root: path.join(rootDir, "admin"),
  // Assets are addressed relative to the folder, so the secret path can change
  // without rebuilding anything but this.
  base: "./",
  define: {
    // In this build every call goes to api.php; locally they go to the Node
    // server's /api/ routes.
    __ADMIN_API__: JSON.stringify("api.php?action="),
  },
  build: {
    outDir,
    emptyOutDir: true,
  },
  logLevel: "warn",
});

/* ------------------------------------------------------------------
   The backend
------------------------------------------------------------------ */

for (const file of ["api.php", ".htaccess"]) {
  fs.copyFileSync(path.join(rootDir, "admin/server", file), path.join(outDir, file));
}

/** Escapes a value for a PHP single-quoted string literal. */
const php = (value) => String(value).split("\\").join("\\\\").split("'").join("\\'");

fs.writeFileSync(
  path.join(outDir, "config.php"),
  `<?php
/**
 * Generated by scripts/build-admin.mjs — do not edit, and never commit.
 *
 * Three things keep this file's contents private, in order: the folder's
 * .htaccess refuses to serve it, PHP executes rather than prints it, and the
 * guard below stops it doing anything if it is reached any other way. If the
 * token is ever exposed anyway, revoke it on GitHub and rebuild.
 */

if (!defined('ADMIN_ENTRY')) {
    http_response_code(404);
    exit;
}

define('ADMIN_PASSWORD_HASH', '${php(env.hash)}');
define('ADMIN_GITHUB_TOKEN', '${php(env.token)}');
define('ADMIN_GITHUB_REPO', '${php(env.repo)}');
define('ADMIN_GITHUB_BRANCH', '${php(env.branch)}');
define('ADMIN_GITHUB_WORKFLOW', '${php(env.workflow)}');
`,
);

// The icon and image choices the editor offers. Read from disk at build time
// because the PHP side cannot parse the JavaScript catalogue.
const images = fs
  .readdirSync(path.join(rootDir, "src/assets"))
  .filter((file) => /^svc-.*\.jpg$/.test(file))
  .map((file) => file.replace(/\.jpg$/, ""))
  .sort();

fs.writeFileSync(
  path.join(outDir, "catalog.json"),
  JSON.stringify(
    { icons: iconCatalog.map(({ name, label }) => ({ name, label })), images },
    null,
    2,
  ) + "\n",
);

const size = fs
  .readdirSync(outDir, { recursive: true, encoding: "utf8" })
  .map((file) => path.join(outDir, file))
  .filter((file) => fs.statSync(file).isFile())
  .reduce((total, file) => total + fs.statSync(file).size, 0);

console.log(
  `\n  Content admin built into dist-static/${env.path}/  (${(size / 1024).toFixed(0)} kB)`,
);
console.log(`  It will be live at  <your site>/${env.path}/  after the next upload.\n`);
